server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp 

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  # sql:
  #   init:
  #     mode: always

  data:
    mongodb:
      uri: mongodb://localhost:27017/portfolio

  jpa:
    # defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      # ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: always

# S3 설정
cloud:
  aws:
    region:
      static: ${static}
      auto: false # false면 자동으로 리전을 선택하지 않고, static 설정을 따름
    s3:
      bucket: ${bucket}
    credentials:
      access-key: ${access-key}
      secret-key: ${secret-key}
    stack:
      auto: false # false로 설정된 경우, CloudFormation 스택은 자동으로 생성되거나 관리되지 않음

# Sentry 설정
sentry:
  dsn: ${sentry-dsn}
  enable-tracing: true
  send-default-pii: true 
  environment: development 
  logging:
    minimum-event-level: "WARN"
    minimum-breadcrumb-level: "INFO"  
  sample-rate: 1


name: ${MY.JWT}