server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp 

  datasource:
    url: jdbc:mysql://localhost:3306/portfolio?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  data:
    mongodb:
      uri: mongodb://localhost:27017/portfolio

  jpa:
    open-in-view: false
    hibernate:
      # ddl-auto: create
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  output:
    ansi:
      enabled: always